### ISSUE TITLE
Domanda sul supporto a PDF/A

### ISSUE THREAD

**Issue by ranghetto** [eliapasquali/typst-thesis-template#4]
Buongiorno, sono a conoscenza del fatto che _Typst_ non supporti nativamene l'export in `PDF/A`, come è indicato anche nel README.
Usare un qualsiasi tool per la conversione da `PDF` a `PDF/A` ci permette di aggirare il problema e usare _Typst_ per scrivere la tesi?
Oppure questo, si tratta di un progetto creato "aspettando" quel tipo di supporto per il futuro?

**Comment by eliapasquali** [comment]
> Usare un qualsiasi tool per la conversione da `PDF` a `PDF/A` ci permette di aggirare il problema e usare _Typst_ per scrivere la tesi?

Ciao, si! Ad esempio, convertendo con il tool di [ilovepdf](https://www.ilovepdf.com/it/pdf-in-pdfa) il risultato è accettato su [pdfforge](https://www.pdfforge.org/online/it/convalida-pdfa).
